#!/bin/bash -eu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)

while getopts ":r:n:u:p:" opt; do
    case "$opt" in
        r) root_pass=$OPTARG;;
        n) db_name=$OPTARG;;
        u) db_user=$OPTARG;;
        p) db_pass=$OPTARG;;
        \?) echo "option -$OPTARG not supported"; exit 1;;
        :) echo "option -$OPTARG requires an argument"; exit 1;;
    esac
done
args="${@:$OPTIND}"

docker run --name db -t -d \
    --volumes-from data-db \
    -e MYSQL_ROOT_PASSWORD=$root_pass \
    -e LS_NAME=$db_name \
    -e LS_USER=$db_user \
    -e LS_PASSWORD=$db_pass \
    -e LS_ROOT_PASSWORD=$root_pass \
    mysql
