#!/bin/bash -eu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)

while [[ $# -gt 0 ]];do
    case "$1" in
        --root_pass) root_pass=$2; shift;;
        --name) name=$2; shift;;
        --user) user=$2; shift;;
        --pass) pass=$2; shift;;
        --*) echo "unsupported option $1"; exit 1;;
        *) break ;;
    esac
    shift
done

echo "root_pass: $root_pass"
echo "name: $name"
echo "user: $user"
echo "pass: $pass"

docker run --name db -t -d \
    --volumes-from data-db \
    -e MYSQL_ROOT_PASSWORD=$root_pass \
    -e LS_NAME=$name \
    -e LS_USER=$user \
    -e LS_PASSWORD=$pass \
    -e LS_ROOT_PASSWORD=$root_pass \
    mysql
