#!/bin/bash
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)

interactive=false
dev_mode=false
while getopts ":id" opt; do
    case $opt in
        i) interactive=true;;
        d) dev_mode=true;;
        \?) echo "Not a supported option $OPTARG"; exit 1;;
    esac
done
args=${@:$OPTIND}

interactive_option="-d"
if [ $interactive = true ];then
    interactive_option="-ti --rm    "
fi

dev_volume=""
if [ $dev_mode = true ];then
    dev_volume="-v $project_root/code/media:/var/lendsnap/media"
fi
docker run --name media $interactive_option \
    $dev_volume \
    -p 3001:3001 \
    media $args
