#!/bin/bash -eu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)
docker run --name nginx-console -ti --rm \
    -v $project_root/code/nginx:/var/lendsnap/nginx \
    --volumes-from data-uploaded \
    --link db:db \
    --link node-webapp:node \
    nginx /bin/bash
