#!/bin/bash -eu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)

dev_mode=false
while getopts ":d" opt; do
    case "$opt" in
        d) dev_mode=true;;
        \?) echo "Invalid option -$OPTARG"; exit 1;;
    esac
done
args=${@:$OPTIND}

dev_volume=""
if [ $dev_mode = true ];then
    dev_volume="-v $project_root/code/nginx:/var/lendsnap/nginx "
fi

docker run --name nginx -t -d \
    $dev_volume \
    --volumes-from data-uploaded \
    -p 80:80 \
    --link db:db \
    --link node-webapp:node \
    nginx
