#!/bin/bash -eu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)
docker run --name node-tests -t --rm \
    -v $project_root/code/node:/var/lendsnap/node \
    --link db:db \
    node node_modules/vows/bin/vows --spec test/*-spec.js
