#!/bin/bash
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; pwd)
find $project_root -type f -name install | while read path; do
  if [[ "$path" = "$project_root/install" ]]; then
    continue
  fi
  echo "$path"
  eval "$path"
done
