#!/bin/bash
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; pwd)
find $project_root -type f -name \*.service | while read path; do
    cmd="sudo systemctl enable $path"
    echo $cmd
    eval $cmd
done
