#!/bin/bash
current_directory=$(cd `dirname ${BASH_SOURCE[0]}`; pwd)

playbook_name=$1
if ! [[ $playbook_name ]];then
    echo "Playbook name required"
fi
playbook_path=$current_directory/ansible/playbooks/$playbook_name.yml
echo "using playbook: $playbook_path"

cd $current_directory # use the ansible.cfg
ansible-playbook --extra-vars="code_directory=$current_directory/code" $playbook_path
