#!/bin/bash -eu
#

developer_name=${1:-}
if [ -z "$developer_name" ]; then
    echo "developer name required as only argument"
    exit 1
fi

user_id=`id -u $developer_name`
group_id=`id -u $developer_name`

if ! [ -e "/home/$developer_name/code" ]; then
    mkdir /home/$developer_name/code
fi

mount \
    -t vboxsf \
    -o rw,uid=$user_id,gid=$group_id \
    /code /home/$developer_name/code
