-   hosts: all
    gather_facts: False
    roles:
        -   defunctzombie.coreos-bootstrap
    tasks:
        # -   name: git repo
        #     git: repo=git://git@github.com:lendsnap/lendsnap dest=/var/lendsnap-repo accept_hostkey=yes
        -   name: Enable systemctl modules
            raw: systemctl enable /var/lendsnap-repo/deploy/services/*.service
            sudo: yes

-   hosts: db
    sudo: yes
    tasks:
    -   name: Pull mysql image
        raw: docker pull mysql
    -   name: Pull docker register image
        raw: docker pull polvi/docker-register

    -   name: Start db
        raw: systemctl start db
    -   name: Start db-register
        raw: systemctl start db-register

-   hosts: webserver
    sudo: yes
    tasks:
    -   name: Pull polvi/dynamic-etcd-amb
        raw: docker pull polvi/dynamic-etcd-amb
    -   name: Build node
        raw: docker build -t node /var/lendsnap-repo/code/node
    -   name: Build nginx proxy
        raw: docker build -t nginx-proxy /var/lendsnap-repo/code/nginx-proxy

    -   name: Start node
        raw: systemctl start node
    -   name: Start nginx
        raw: systemctl start nginx-proxy
