-   hosts: db
    tasks:
    -   name: Start db data
        command: >
            {{ project_root }}/ansible/commands/data-db-start
        ignore_errors: true

    -   name: Stop db
        command: docker rm -f db
        ignore_errors: true

    -   name: Start db
        command: >
            {{ project_root }}/ansible/commands/db-start
                -r {{ db_root_password }}
                -n {{ db_name }}
                -u {{ db_user }}
                -p {{ db_password }}

-   hosts: media
    tasks:
    -   name: Start uploaded data
        command: >
            {{ project_root }}/ansible/commands/data-uploaded-start
        ignore_errors: true

    -   name: Build media
        command: >
            {{ project_root }}/ansible/commands/media-build
    -   name: Stop media
        command: >
            docker rm -f media
        ignore_errors: true
    -   name: Start media
        command: >
            {{ project_root }}/ansible/commands/media-start {{ dev_mode_option }}

-   hosts: node
    tasks:
    -   name: Start uploaded data
        command: >
            {{ project_root }}/ansible/commands/data-uploaded-start
        ignore_errors: true

    -   name: Stop node
        command: docker rm -f node
        ignore_errors: true

    -   name: Build node
        command: >
            {{ project_root }}/ansible/commands/node-build

    -   name: Start node
        command: >
            {{ project_root }}/ansible/commands/node-start {{ dev_mode_option }}


-   hosts: nginx_proxy
    tasks:
    -   name: Start uploaded data
        command: >
            {{ project_root }}/ansible/commands/data-uploaded-start
        ignore_errors: true

    -   name: Stop nginx proxy
        command: docker rm -f nginx-proxy
        ignore_errors: true

    -   name: Build nginx proxy
        command: >
            {{ project_root }}/ansible/commands/nginx-proxy-build

    -   name: Start nginx proxy
        command: >
            {{ project_root }}/ansible/commands/nginx-proxy-start {{ dev_mode_option }}
