# TODO: make mounting local directory optional

-   hosts: all
    connection: local
    tasks:
    -   include: ../tasks/db.yml
    -   include: ../tasks/node.yml
    -   include: ../tasks/nginx.yml
