-   hosts: all
    connection: local
    gather_facts: False
    tasks:
        -   name: Stop all docker processes
            shell: "docker ps -a | grep -v CONT | awk '{print $1}' | xargs docker rm -f"
