-   name: Stop db
    command: docker rm -f db
    ignore_errors: true

-   name: Start db
    command: >
        {{ project_root }}/ansible/commands/db-start
            --root_pass a
            --name lendsnap
            --user lendsnap
            --pass a
