-   name: Stop nginx
    command: docker rm -f nginx
    ignore_errors: true

-   name: Build nginx
    command: >
        docker build -t nginx {{ project_root }}/code/nginx

-   name: Start nginx
    command: >
        {{ project_root }}/ansible/commands/nginx-start

