#!/bin/bash
host=`cat /etc/private_ipv4`
port=3306
root_password=a
password=a
user=lendsnap
name=lendsnap
value="{\"host\": \"$host\", \"port\": \"$port\",\
    \"root_password\": \"$root_password\", \"password\": \"$password\", \
    \"name\": \"$name\", \"user\": \"$user\"}"
while true; do
    echo "setting $value"
    etcdctl set /services/db "$value" --ttl 11
    sleep 10s
done
