#!/bin/bash
sudo systemctl enable /var/lendsnap-repo/data/data-db.service
sudo systemctl enable /var/lendsnap-repo/db/db.service
sudo systemctl enable /var/lendsnap-repo/db/db-announce.service
docker pull mysql
