#!/bin/bash -x
/var/lendsnap-repo/base-node/install
/var/lendsnap-repo/media/install
sudo systemctl enable /var/lendsnap-repo/data/data-uploaded.service

docker build -t web-ui /var/lendsnap-repo/web-ui
sudo systemctl enable /var/lendsnap-repo/web-ui/web-ui.service
sudo systemctl enable /var/lendsnap-repo/web-ui/web-ui-db-setup.service
