#!/bin/bash
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ..; pwd)
image_name=${1:-}
if ! [[ "$image_name" ]]; then
    echo "Image name is required."
    exit 1
fi
ip_address=`docker inspect --format='{{.NetworkSettings.IPAddress}}' $image_name`

mkdir -p $HOME/.ssh
cp $project_root/base-node/root_id_rsa $HOME/.ssh/
chmod 0600 $HOME/.ssh/root_id_rsa

set -x
ssh -i $HOME/.ssh/root_id_rsa -o "StrictHostKeyChecking no" root@$ip_address
