#!/bin/bash -xu
project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ..; pwd)
cd $project_root
if ! [ -e "$project_root/.ssh-config" ]; then
    vagrant ssh-config > $project_root/.ssh-config
fi
computer_name="$(hostname | tr '[:lower:]' '[:upper:]')"

if `net share lendsnap /delete >/dev/null 2>&1`; then
    echo "Deleted old share"
fi
net share lendsnap=$(cygpath -d $project_root) /grant:Everyone,FULL
echo "Sharing $project_root as \"lendsnap\""

server_names="$(awk '/^Host/{print $2}' $project_root/.ssh-config | xargs echo)"
for server_name in $server_names; do
    scp -F $project_root/.ssh-config $project_root/mount.cifs core@$server_name:~
    ssh -t -F $project_root/.ssh-config core@$server_name <<EOF
        set -x;
        sudo umount /var/lendsnap-repo >/dev/null 2>&1;
        (test -e /var/lendsnap-repo || sudo mkdir /var/lendsnap-repo);
        sudo chown core /var/lendsnap-repo;
        sudo ./mount.cifs //$computer_name/lendsnap /var/lendsnap-repo\
            -oguest,rw,uid=core;
        echo Mounted;
EOF
done
#rm $project_root/.ssh-config
