-   hosts: coreos
    gather_facts: False
    roles:
        -   defunctzombie.coreos-bootstrap

-   hosts: all
    tasks:
        # -   name: git repo
        #     git: repo=git://git@github.com:lendsnap/lendsnap dest=/var/lendsnap-repo accept_hostkey=yes
        -   name: Enable systemctl modules
            raw: systemctl enable /var/lendsnap-repo/deploy/services/*.service
            sudo: yes

-   hosts: db
    tasks:
    -   raw: /var/lendsnap-repo/db/install
    -   raw: fleetctl start db

-   hosts: webapp
    tasks:
    -   raw: /var/lendsnap-repo/web-ui/install
    -   raw: fleetctl start web-ui
